### PR TITLE
Use not existing

### PR DESCRIPTION
**Pull request by kpanic**
Hey there! 👋🏾 

I created some small PRs to use "Not existing". 
Hope they are fine.

Thanks for these great projects! 💯

### CODE REVIEW

**Comment by lorenzosinisi** [comment]
LGTM thanks!

**Comment by lorenzosinisi** [comment]
Doe sanskrit still work fine with this renaming?

**Comment by kpanic** [comment]
tests are green @lorenzosinisi

**Comment by lorenzosinisi** [comment]
I will add a test with https://github.com/lorenzosinisi/sanskrit/blob/master/lib/parser.ex#L165C11-L165C31 might break when using it

**Comment by kpanic** [comment]
It might be covered by this https://github.com/lorenzosinisi/sanskrit/blob/master/test/sanskrit_test.exs#L173 (renamed)

**Comment by lorenzosinisi** [comment]
> It might be covered by this https://github.com/lorenzosinisi/sanskrit/blob/master/test/sanskrit_test.exs#L173 (renamed)

perfect! Yep I saw that only later 👍 Good stuff!

**Pull request merged**
